name: Wagewatch-OvertimeLog
options:
  bundleIdPrefix: com.shimondeitel.wagewatch
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Wagewatch-OvertimeLog:
    type: application
    platform: iOS
    sources:
      - path: Wagewatch-OvertimeLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.wagewatch
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Wagewatch-OvertimeLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  Wagewatch-OvertimeLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Wagewatch-OvertimeLogTests
      - path: Wagewatch-OvertimeLog.storekit
    dependencies:
      - target: Wagewatch-OvertimeLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.wagewatch.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  Wagewatch-OvertimeLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Wagewatch-OvertimeLogUITests
    dependencies:
      - target: Wagewatch-OvertimeLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.wagewatch.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Wagewatch-OvertimeLog:
    build:
      targets:
        Wagewatch-OvertimeLog: all
        Wagewatch-OvertimeLogTests: [test]
        Wagewatch-OvertimeLogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Wagewatch-OvertimeLog.storekit
    test:
      config: Debug
      storeKitConfiguration: Wagewatch-OvertimeLog.storekit
      targets:
        - Wagewatch-OvertimeLogTests
        - Wagewatch-OvertimeLogUITests
    archive:
      config: Release
